version: 2
jobs:
  build:
    working_directory: ~/3box-dapp
    docker:
      - image: circleci/node:10
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}

      - run:
          name: install-awscli-and-dependencies
          command: |
            sudo apt-get update && sudo apt-get install awscli
            npm i

      - run:
          name: run-tests
          command: |
            npm test

      - run:
          name: deploy-to-s3
          command: |
            CI=false NODE_OPTIONS=--max_old_space_size=8192 npm run build
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              # Fix Warnings CI=false is just a baaad workaround
              npm run deploy-develop
              chmod +x cache.sh
              ./cache.sh develop
              npm run invalidate E17Q4403A4B4C8
            fi
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run deploy-master
              chmod +x cache.sh
              ./cache.sh master
              npm run invalidate ET1S25F7JOQM6
            fi
            if [[ "${CIRCLE_BRANCH}" == *"release/"* ]]; then
              npm run deploy-test
              chmod +x cache.sh
              ./cache.sh test
              npm run invalidate E256JNRDZ1B3QM
            fi

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build