version: 2
jobs:
  build:
    working_directory: ~/3box-dapp
    docker:
      - image: circleci/node:10
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}

      - run:
          name: install-awscli-and-dependencies
          command: |
            sudo apt-get update && sudo apt-get install awscli
            npm i

      - run:
          name: run-tests
          command: |
            npm test

      - run:
          name: deploy-to-s3
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              # Fix Warnings CI=false is just a baaad workaround
              CI=false npm run build
              npm run deploy-develop
              aws s3 cp s3://3box-dapp-develop.3box.io/service-worker.js s3://3box-dapp-develop.3box.io/service-worker.js --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type application/javascript --acl public-read
              aws s3 cp s3://3box-dapp-develop.3box.io/index.html s3://3box-dapp-develop.3box.io/index.html --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html --acl public-read
              npm run invalidate E17Q4403A4B4C8
            fi
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              CI=false npm run build
              npm run deploy-master
              aws s3 cp s3://3box-dapp-master.3box.io/service-worker.js s3://3box-dapp-master.3box.io/service-worker.js --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type application/javascript --acl public-read
              aws s3 cp s3://3box-dapp-master.3box.io/index.html s3://3box-dapp-master.3box.io/index.html --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html --acl public-read
              npm run invalidate ET1S25F7JOQM6
            fi
            if [[ "${CIRCLE_BRANCH}" == *"release/"* ]]; then
              CI=false npm run build
              npm run deploy-test
              aws s3 cp s3://3box-dapp-test.3box.io/service-worker.js s3://3box-dapp-test.3box.io/service-worker.js --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type application/javascript --acl public-read
              aws s3 cp s3://3box-dapp-test.3box.io/index.html s3://3box-dapp-test.3box.io/index.html --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html --acl public-read
              npm run invalidate E256JNRDZ1B3QM
            fi

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build